deploy:
  provider: heroku
<<<<<<< Updated upstream
  api_key: "E4TY15f4x+SBFmmBNWkMEi8BOIyrGAjpvoodThv92AR5s58FgzoZwe2ruVsPfyrp+ts/hdoD4BciBzKeNYQyEo9kRk6b4lI3UD0Z2xJ4/mmiygygRk2bOA0GvTSgflDUXsyo8Af0SmpDk9yot5+JbfWh8TRBeW12AdD13o9u1xw="
  app: my-curiocity
=======
  api_key:
    secure: sU0b+4PcLOC9AXjncS+maWxxBpkP1syZ19EMNXDgZzgxjuBN9gSrDIUBF0SwIRhsFgBnXAbr8s5fv9bBKMVrrFLhttXodEXlEFLwI1xUAUtqX86vEb0rNrWG/s5joBaCWavoWpI3YEmRNyPJ6XR03w50gHdkBFyX/4zZayE1VV4=
  app: 
    master: project-curiocity
    development: project-curiocity-beta
  on:
    repo: ULRL-Lab/curiocity-test
>>>>>>> Stashed changes
